export const commentsData = [
  {
    id: 0,
    videoId: 'vid_101',
    comment: 'This scene is amazing!',
    timestamp: '00:2',
    cmdTime: '2025-09-03T12:45:30Z',
    profileUrl: 'https://randomuser.me/api/portraits/men/12.jpg',
    name: 'John Doe',
  },
  {
    id: 2,
    videoId: 'vid_101',
    comment: 'Lol this part made me laugh 😂',
    timestamp: '00:5',
    cmdTime: '2025-09-03T12:46:15Z',
    profileUrl: 'https://randomuser.me/api/portraits/women/34.jpg',
    name: 'Emily Smith',
  },
  {
    id: 3,
    videoId: 'vid_102',
    comment: 'Can someone explain what just happened?',
    timestamp: '00:09',
    cmdTime: '2025-09-03T12:50:10Z',
    profileUrl: 'https://randomuser.me/api/portraits/men/56.jpg',
    name: 'Michael Johnson',
  },
  {
    id: 4,
    videoId: 'vid_103',
    comment: 'Background music is 🔥🔥',
    timestamp: '00:14',
    cmdTime: '2025-09-03T12:53:42Z',
    profileUrl: 'https://randomuser.me/api/portraits/women/76.jpg',
    name: 'Sophia Lee',
  },
  {
    id: 5,
    videoId: 'vid_103',
    comment: 'I didn’t expect that twist!',
    timestamp: '00:01',
    cmdTime: '2025-09-03T12:55:00Z',
    profileUrl: 'https://randomuser.me/api/portraits/men/85.jpg',
    name: 'David Brown',
  },
];
